name: End-to-end tests ðŸ§ª
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.14.0
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
          cache: "npm"

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: npm ci

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
